### ISSUE TITLE
FTweaks Error 

### ISSUE THREAD

**Issue by Subz91** [NotTotal/Total-Skyrim-Overhaul#9]
When the installation is finishing this error appears to me, does anyone know how to solve it?

Thanks.

"234,23 - Getting Nexus API Key, if a browser appears, please accept
234,23 - File hash check (-42) f0ebd9accd78773ea866f45be152973e04aa1efb2dcf7bbe14a38758a82a4862
234,23 - Downloading FTweaks-44044-0-4-1610379482.7z
236,16 - Nexus call failed `https://api.nexusmods.com/v1/games/skyrimspecialedition/mods/44044/files/178966/download_link.json`: Wabbajack.Common.Exceptions.HttpException: Http Error NotFound - Not Found
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.NexusApi.NexusApiClient.Get[T](String url, Client client) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\NexusApi\NexusApi.cs:line 264
237,93 - Trying to find solution to broken download for FTweaks-44044-0-4-1610379482.7z
241,82 - Downloading possible upgrade NexusDownloader+State|SkyrimSpecialEdition|44044|179756
243,71 - Possible upgrade NexusDownloader+State|SkyrimSpecialEdition|44044|179756 downloaded
243,71 - Looking for patch for FTweaks-44044-0-4-1610379482.7z (-5343704847011264209 2f495cf9c058d7b5 -> 305968701250236877 cd7168a6e9043f04)
245,21 - Download error for file FTweaks-44044-0-4-1610379482.7z
245,21 - Wabbajack.Common.Exceptions.HttpException: Http Error BadRequest - Bad Request
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.PostAsync(String url, HttpContent content, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 36
   at Wabbajack.Lib.ClientAPI.GetModUpgrade(Archive oldArchive, Archive newArchive, Nullable`1 maxWait, Nullable`1 waitBetweenTries, Boolean useAuthor) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ClientAPI.cs:line 102
   at Wabbajack.Lib.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\DownloadDispatcher.cs:line 140
   at Wabbajack.Lib.AInstaller.DownloadArchive(Archive archive, Boolean download, Nullable`1 destination) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 263
245,21 - Hashing Remaining Archives
245,21 - Looking for files to hash
245,23 - Found 660 total files, 645 matching filesize
245,3 - Unable to download FTweaks-44044-0-4-1610379482.7z (NexusDownloader+State|SkyrimSpecialEdition|44044|178966)
245,3 - Cannot continue, was unable to download one or more archives
245,3 - Vacuuming databases
245,3 - Vacuuming completed
245,3 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 67
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 146
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__62_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 176
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 168
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 162
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__74>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 374"

**Comment by Subz91** [comment]
Solved.

**Comment by drager773** [comment]
how did you solve it? im getting the same error about not being able to download ftweaks.
